#' RFPCA: Riemannian Functional Principal Component Analysis
#'
#' RFPCA for Functional Data Analysis of Riemannian manifold data
#' 
#' Desc
#' 
#' References: Wang, J.L., Chiou, J.,  Müller, H.G. (2016). Functional data analysis. Annual Review of Statistics and Its Application 3, 257--295
#' Chen, K., Zhang, X., Petersen, A., Müller, H.G.  (2017). Quantifying infinite-dimensional data: Functional Data Analysis in action. 
#' Statistics in Biosciences 9, 582–-604.
#' 
#' Links for fda-pace/PACE:
#' Matlab version of pace at http://anson.ucdavis.edu/~mueller/data/pace.html
#' Papers and background at http://anson.ucdavis.edu/~mueller/  and  http://www.stat.ucdavis.edu/~wang/
#' 
#' 
#' 
#' PACE is based on the idea that observed functional data
#' are generated by a sample of underlying (but usually not fully
#' observed) random trajectories that are realizations of a stochastic process. It does not rely on pre-smoothing of
#' trajectories, which is problematic if functional data are sparsely sampled.
#' 
#' The functional principal components can be used for further statistical analysis depending on 
#' the demands of a user, for example if one has densely sampled functional predictors and a generalized 
#' response, such as in a GLM, the predictor functions can be replaced by their first couple of principal component scores that
#' will then be used as predictors; one can also easily fit polynomial functional models by using powers (usually squares) 
#' and interactions of functional principal 
#' components among the predictors for a scalar response. 
#' 
#' fda-pace is a comprehensive package that directly implements fitting of the following models:
#' -- functional linear regression 
#' -- functional additive regression
#' -- functional covariance and correlation (via dynamic correlation) 
#' -- functional clustering 
#' -- concurrent (varying coefficient) regression models for sparse and dense designs
#' -- varying coefficient additive models
#' -- multivariate functional data analysis (normalization and functional singular component analysis)
#' -- variance processes and volatility processes (the latter of interest in finance)
#' -- optimal designs for longitudinal data analysis (for trajectory prediction and for functional linear regression) 
#' -- stringing, a method to convert high-dimensional data into functional data
#' -- quantile regression, with functions as predictors
#'  
#'  
#' 
#' Maintainer:  Xiongtao Dai \email{xdai@@iastate.edu}
#' 
#' @author
#' Xiongtao Dai \email{xdai@@iastate.edu}
#' Zhenhua Lin
#' Hans-Georg Müller
#'
#'
#' 
#'
#' @docType package
#' @name RFPCA
#' @useDynLib RFPCA
# #' @import Rcpp
# #' @importFrom Matrix Matrix
# #' @importFrom Hmisc approxExtrap
# #' @importFrom pracma meshgrid midpoint mod ones uniq
# #' @importFrom numDeriv grad hessian
# #' @importFrom grDevices colorRampPalette dev.new palette
# #' @importFrom graphics abline barplot boxplot grid legend lines matlines matplot par plot points polygon 
# #' @importFrom stats aggregate approx approxfun binomial cov dist fitted glm kmeans lm median na.omit optim predict quantile rnorm runif spline var sd poly weighted.mean cor dunif
# #' @importFrom utils head tail
# #' @importFrom MASS isoMDS mvrnorm
NULL
