# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distSO <- function(X, Y) {
    .Call('_RFPCA_distSO', PACKAGE = 'RFPCA', X, Y)
}

logSO <- function(p, X) {
    .Call('_RFPCA_logSO', PACKAGE = 'RFPCA', p, X)
}

#' Matrix exponential
#'
#' \code{ExpM(X)} computes the matrix exponential using Armardillo. 
#'
#' @param X An SPD matrix 
#'
#' @export
ExpM <- function(X) {
    .Call('_RFPCA_ExpM', PACKAGE = 'RFPCA', X)
}

#' Matrix logarithm
#'
#' \code{LogM(X)} computes the matrix logarithm of a general matrix using Armardillo. The returned value is a complex matrix.
#'
#' @export
LogM <- function(X) {
    .Call('_RFPCA_LogM', PACKAGE = 'RFPCA', X)
}

#' Matrix logarithm of a symmetric positive definite
#'
#' \code{LogMSPD(X)} computes the matrix logarithm of an SPD matrix using Armardillo. The returned value is a real matrix.
#'
#' @export
LogMSPD <- function(X) {
    .Call('_RFPCA_LogMSPD', PACKAGE = 'RFPCA', X)
}

distAffInv11 <- function(X, Y) {
    .Call('_RFPCA_distAffInv11', PACKAGE = 'RFPCA', X, Y)
}

distAffInv11_2 <- function(X, Y) {
    .Call('_RFPCA_distAffInv11_2', PACKAGE = 'RFPCA', X, Y)
}

distAffInv1m <- function(X, Y) {
    .Call('_RFPCA_distAffInv1m', PACKAGE = 'RFPCA', X, Y)
}

distAffInv <- function(X, Y) {
    .Call('_RFPCA_distAffInv', PACKAGE = 'RFPCA', X, Y)
}

logAffInv <- function(p, X) {
    .Call('_RFPCA_logAffInv', PACKAGE = 'RFPCA', p, X)
}

